platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "9"
inputs:
  - name: sources
outputs:
  - name: build
params:
  JDK_VERSION: 9
run:
  path: sources/ci/tasks/build.sh