platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"
inputs:
  - name: sources
outputs:
  - name: build
params:
  OSSRHUSER:
  OSSRHPASSWORD:
run:
  path: sources/ci/tasks/build.sh