resources:
- name: sources
  type: git
  source:
    uri: https://github.com/alek-sys/dataj

jobs:
- name: build
  plan:
    - get: sources
      trigger: true
    - task: build
      file: sources/ci/tasks/build.yml